package xray

import (
	"fmt"
	"net"
	"os/exec"
	"regexp"
	"sort"
	"strings"

	"github.com/taiiok/xiaomi-vless/internal/config"
)

var ipv4Pattern = regexp.MustCompile(`^([0-9]{1,3}\.){3}[0-9]{1,3}$`)

// GenerateIPTablesScript builds an iptables helper script for active VPN nodes.
func GenerateIPTablesScript(cfg config.PanelConfig, nodes []config.Node) (string, error) {
	cfg.Normalize()
	subnet := cfg.Iptables.GuestSubnet
	if subnet == "" {
		subnet = cfg.Network.GuestSubnet
	}
	if subnet == "" {
		return "", fmt.Errorf("guest subnet is empty")
	}

	ips, hosts := collectBypassTargets(nodes)
	sort.Strings(ips)
	sort.Strings(hosts)

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by Xiaomi VLESS Panel — do not edit manually.\n\n")
	b.WriteString(fmt.Sprintf("GUEST_SUBNET=%q\n", subnet))
	b.WriteString(fmt.Sprintf("TCP_PORT=%d\nUDP_PORT=%d\nMARK=0x1\nTABLE=100\n\n", cfg.Iptables.TCPPort, cfg.Iptables.UDPPort))

	b.WriteString("resolve_host() {\n")
	b.WriteString("  HOST=\"$1\"\n")
	b.WriteString("  echo \"$HOST\" | grep -qE '^([0-9]{1,3}\\.){3}[0-9]{1,3}$' && echo \"$HOST\" && return\n")
	b.WriteString("  IP=$(nslookup \"$HOST\" 2>/dev/null | awk '/^Address [0-9]*:/{print $NF}' | tail -1)\n")
	b.WriteString("  echo \"$IP\" | grep -qE '^([0-9]{1,3}\\.){3}[0-9]{1,3}$' && echo \"$IP\" && return\n")
	b.WriteString("  IP=$(ping -c 1 -W 3 \"$HOST\" 2>/dev/null | sed -n 's/.*(\\([0-9.]*\\)).*/\\1/p')\n")
	b.WriteString("  echo \"$IP\" | grep -qE '^([0-9]{1,3}\\.){3}[0-9]{1,3}$' && echo \"$IP\" && return\n")
	b.WriteString("  echo \"\"\n")
	b.WriteString("}\n\n")

	b.WriteString("VPN_IPS=\"")
	b.WriteString(strings.Join(ips, " "))
	b.WriteString("\"\n")
	for _, host := range hosts {
		b.WriteString(fmt.Sprintf("IP=$(resolve_host %q); [ -n \"$IP\" ] && VPN_IPS=\"$VPN_IPS $IP\"\n", host))
	}
	b.WriteString("\n")

	b.WriteString("sysctl -w net.ipv4.ip_forward=1 >/dev/null\n")
	b.WriteString("sysctl -w net.ipv4.conf.all.rp_filter=0 >/dev/null\n")
	b.WriteString("sysctl -w net.ipv4.conf.br-guest.rp_filter=0 >/dev/null\n")
	b.WriteString("sysctl -w net.ipv4.conf.eth0.rp_filter=0 >/dev/null\n\n")

	b.WriteString("ip rule del fwmark $MARK table $TABLE 2>/dev/null\n")
	b.WriteString("ip rule add fwmark $MARK table $TABLE\n")
	b.WriteString("ip route flush table $TABLE 2>/dev/null\n")
	b.WriteString("ip route add local 0.0.0.0/0 dev lo table $TABLE\n\n")

	writeChainRules(&b, "nat", "XRAY_GUEST_TCP", "tcp", "REDIRECT", "$TCP_PORT", "$VPN_IPS")
	writeChainRules(&b, "mangle", "XRAY_GUEST_UDP", "udp", "TPROXY", "$UDP_PORT", "$VPN_IPS")

	b.WriteString("iptables -t nat -F XRAY_DNS 2>/dev/null\n")
	b.WriteString("iptables -t nat -D PREROUTING -j XRAY_DNS 2>/dev/null\n\n")
	b.WriteString("echo \"Rules applied. VPN bypass IPs:${VPN_IPS}\"\n")

	return b.String(), nil
}

func writeChainRules(b *strings.Builder, table, chain, proto, action, portVar, vpnIPsVar string) {
	b.WriteString(fmt.Sprintf("iptables -t %s -N %s 2>/dev/null\n", table, chain))
	b.WriteString(fmt.Sprintf("iptables -t %s -F %s\n\n", table, chain))

	for _, cidr := range []string{
		"0.0.0.0/8", "10.0.0.0/8", "127.0.0.0/8", "169.254.0.0/16",
		"172.16.0.0/12", "192.168.0.0/16", "224.0.0.0/4", "240.0.0.0/4",
	} {
		b.WriteString(fmt.Sprintf("iptables -t %s -A %s -s $GUEST_SUBNET -d %s -j RETURN\n", table, chain, cidr))
	}

	b.WriteString(fmt.Sprintf("for IP in %s; do\n", vpnIPsVar))
	b.WriteString(fmt.Sprintf("  iptables -t %s -A %s -s $GUEST_SUBNET -d $IP -j RETURN\n", table, chain))
	b.WriteString("done\n\n")

	if action == "REDIRECT" {
		b.WriteString(fmt.Sprintf("iptables -t %s -A %s -s $GUEST_SUBNET -p %s -j REDIRECT --to-ports %s\n\n", table, chain, proto, portVar))
	} else {
		b.WriteString(fmt.Sprintf("iptables -t %s -A %s -s $GUEST_SUBNET -p %s -j TPROXY --tproxy-mark $MARK --on-port %s\n\n", table, chain, proto, portVar))
	}

	b.WriteString(fmt.Sprintf("iptables -t %s -D PREROUTING -j %s 2>/dev/null\n", table, chain))
	b.WriteString(fmt.Sprintf("iptables -t %s -A PREROUTING -j %s\n\n", table, chain))
}

func collectBypassTargets(nodes []config.Node) (ips []string, hosts []string) {
	seenIP := map[string]struct{}{}
	seenHost := map[string]struct{}{}
	for _, node := range nodes {
		host := strings.TrimSpace(strings.ToLower(node.Address))
		if host == "" {
			continue
		}
		if ip := net.ParseIP(host); ip != nil && ip.To4() != nil {
			v := ip.String()
			if _, ok := seenIP[v]; !ok {
				seenIP[v] = struct{}{}
				ips = append(ips, v)
			}
			continue
		}
		if resolved := resolveHostGo(host); len(resolved) > 0 {
			for _, v := range resolved {
				if _, ok := seenIP[v]; !ok {
					seenIP[v] = struct{}{}
					ips = append(ips, v)
				}
			}
			continue
		}
		if _, ok := seenHost[host]; !ok {
			seenHost[host] = struct{}{}
			hosts = append(hosts, host)
		}
	}
	return ips, hosts
}

func resolveHostGo(host string) []string {
	if ips, err := net.LookupIP(host); err == nil {
		out := make([]string, 0, len(ips))
		for _, ip := range ips {
			if v4 := ip.To4(); v4 != nil {
				out = append(out, v4.String())
			}
		}
		if len(out) > 0 {
			return out
		}
	}

	out, err := exec.Command("nslookup", host).Output()
	if err != nil {
		return nil
	}
	lines := strings.Split(string(out), "\n")
	var ips []string
	for _, line := range lines {
		if strings.HasPrefix(line, "Address") {
			fields := strings.Fields(line)
			if len(fields) == 0 {
				continue
			}
			candidate := fields[len(fields)-1]
			if ipv4Pattern.MatchString(candidate) {
				ips = append(ips, candidate)
			}
		}
	}
	return ips
}

func ActiveNodes(cfg config.PanelConfig) ([]config.Node, error) {
	return selectedNodes(cfg)
}
